---
- name: Jeffify your Pi
  hosts: all
  become: true
  become_method: sudo
  become_user: root

  tasks:

    - name: Install Samba
      ansible.builtin.apt:
        name: samba
        state: present
        update_cache: true

    - name: Update smb.conf
      ansible.builtin.blockinfile:
        path: /etc/samba/smb.conf
        marker: "# {mark} ANSIBLE MANAGED BLOCK - Jeffify Samba"
        block: |
          [pi]
          path = /home/{{ ansible_user }}
          only guest = no
          browsable = yes
          writeable = yes
          create mask = 0777
          directory mask = 0777
          public = yes
      notify: Restart Samba

    - name: Set GPU memory
      ansible.builtin.lineinfile:
        path: /boot/config.txt
        regexp: '^gpu_mem='
        line: 'gpu_mem=256'

    - name: Install pip3
      ansible.builtin.apt:
        name: python3-pip
        state: present

    - name: Update .bashrc for connecting user
      ansible.builtin.blockinfile:
        path: "~{{ ansible_user }}/.bashrc"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - Jeffify"
        block: |
          set -o vi
          unalias ls 2>/dev/null
          export EDITOR=vi
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

  handlers:

    - name: Restart Samba
      ansible.builtin.service:
        name: smbd
        state: restarted

